### ISSUE TITLE
agentscope.exception.AgentCallError: AgentCallError[localhost:13000]: Failed to update result: timeout

### ISSUE THREAD

**Issue by Falam917** [TangJiakai/GenSim#1]
请问这个问题如何解决呀？
电脑配置Windows i9多核 +4090 
配合ubuntu 4x3090卡部署的embedding 和 llm service的4个api，经过测试embedding和llm的api都可以正常访问输出返回值。
![gensim_launchserver](https://github.com/user-attachments/assets/ad2ce52f-d676-4e45-8636-c14c59ff3db3)
![gensim_agenterror](https://github.com/user-attachments/assets/6f690279-e2f8-4118-8218-3c017bef89be)

**Comment by TangJiakai** [comment]
您好，抱歉回复迟了。
请问您这个有正常启动 agent server 吗？
